//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string Employee_ID { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string Gender { get; set; }
        public System.DateTime DOB { get; set; }
        public long Mobile { get; set; }
        public string Department { get; set; }
        public string Designation { get; set; }
        public string Work_Email_ID { get; set; }
        public string Blood_Type { get; set; }
        public System.DateTime DOJ { get; set; }
        public Nullable<System.DateTime> DOQ { get; set; }
        public string ID_Proof_Type { get; set; }
        public string ID_Proof_Number { get; set; }
        public bool IsAdmin { get; set; }
        public string Address { get; set; }
        public string ResetPasswordLink { get; set; }
        public string Token { get; set; }
    
        public virtual Employee Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        public virtual Employee Employee11 { get; set; }
        public virtual Employee Employee3 { get; set; }
        public virtual Employee Employee12 { get; set; }
        public virtual Employee Employee4 { get; set; }
    }
}
